import type { Metadata } from "next";
import { Inter, Titillium_Web } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { cn } from "./lib/utils";
import UpperBar from "./components/UpperBar";
import Image from "next/image";
import dictionary from "../../public/icons/book-open.svg";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });
const titilliumWeb = Titillium_Web({
  weight: ["200", "300", "400", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(titilliumWeb.className, "flex slate-900 h-full")}>
        {" "}
        <Sidebar />
        <div className="flex flex-col w-full">{children}</div>
        <Toaster richColors />
      </body>
    </html>
  );
}
